name: Deploy to Gemfury (Legacy)

on:
  # Allow manual runs of workflow from Actions tab
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'debian/changelog'

jobs:
  sbuild:
    runs-on: 'ubuntu-20.04'

    strategy:
      matrix:
        distro: [buster]
        arch: [armhf]

    environment: GEMFURY

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: sbuild on ${{ matrix.distro }} ${{ matrix.arch }}
        uses: wlan-pi/sbuild-debian-package@main
        id: build-debian-package
        with:
          distro: ${{ matrix.distro }}
          arch: ${{ matrix.arch }}

      - name: Archive artifacts and upload to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: wlanpi-profiler-${{ matrix.distro }}-${{ matrix.arch }}
          path: ${{ steps.build-debian-package.outputs.deb-package }}
          
      - name: Upload Package to Gemfury
        uses: danielmundi/upload-gemfury@main
        with:
          package-name: ${{ steps.build-debian-package.outputs.deb-package }}
          gemfury-username: ${{ secrets.GEMFURY_NAME }}
          gemfury-token: ${{ secrets.GEMFURY_TOKEN }}
  
  slack-workflow-status:
    if: always()
    name: Post Workflow Status to Slack
    needs:
      - sbuild
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          icon_emoji: ':page_facing_up:'
          name: 'WLAN Pi CI Bot'